// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Tickty.Migrations
{
    [DbContext(typeof(TicktyContext))]
    [Migration("20240518063839_t")]
    partial class t
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Tickty.Models.Bill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("QrCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TicketId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TicketId");

                    b.HasIndex("UserId");

                    b.ToTable("Bills");
                });

            modelBuilder.Entity("Tickty.Models.Match", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Referee")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StadiumId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.Property<string>("Team1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Team2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("StadiumId");

                    b.ToTable("Matches");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2024, 5, 18, 9, 38, 38, 961, DateTimeKind.Local).AddTicks(485),
                            Description = "Description 1",
                            Referee = "Referee 1",
                            StadiumId = 1,
                            StartTime = new TimeSpan(0, 18, 0, 0, 0),
                            Team1 = "Team A",
                            Team2 = "Team B"
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2024, 5, 19, 9, 38, 38, 961, DateTimeKind.Local).AddTicks(536),
                            Description = "Description 2",
                            Referee = "Referee 2",
                            StadiumId = 2,
                            StartTime = new TimeSpan(0, 19, 0, 0, 0),
                            Team1 = "Team C",
                            Team2 = "Team D"
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2024, 5, 20, 9, 38, 38, 961, DateTimeKind.Local).AddTicks(540),
                            Description = "Description 3",
                            Referee = "Referee 3",
                            StadiumId = 3,
                            StartTime = new TimeSpan(0, 20, 0, 0, 0),
                            Team1 = "Team E",
                            Team2 = "Team F"
                        });
                });

            modelBuilder.Entity("Tickty.Models.Stadium", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SeatCount")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Stadiums");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Description 1",
                            Image = "stad5.jpg",
                            Location = "Location 1",
                            Name = "Cairo",
                            SeatCount = "10000"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Description 2",
                            Image = "p-min.jpg",
                            Location = "Location 2",
                            Name = "Ahly",
                            SeatCount = "20000"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Description 3",
                            Image = "stad3.jpg",
                            Location = "Location 3",
                            Name = "Campno",
                            SeatCount = "15000"
                        });
                });

            modelBuilder.Entity("Tickty.Models.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MatchId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TicketCount")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.ToTable("Tickets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Ticket for Match 1",
                            MatchId = 1,
                            Price = 50.00m,
                            TicketCount = 500,
                            Type = "Standard"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Ticket for Match 2",
                            MatchId = 2,
                            Price = 75.00m,
                            TicketCount = 400,
                            Type = "Premium"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Ticket for Match 3",
                            MatchId = 3,
                            Price = 60.00m,
                            TicketCount = 300,
                            Type = "Standard"
                        });
                });

            modelBuilder.Entity("Tickty.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Tickty.Models.Bill", b =>
                {
                    b.HasOne("Tickty.Models.Ticket", "Ticket")
                        .WithMany("Bills")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tickty.Models.User", "User")
                        .WithMany("Bills")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ticket");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Tickty.Models.Match", b =>
                {
                    b.HasOne("Tickty.Models.Stadium", "Stadium")
                        .WithMany("Matches")
                        .HasForeignKey("StadiumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stadium");
                });

            modelBuilder.Entity("Tickty.Models.Ticket", b =>
                {
                    b.HasOne("Tickty.Models.Match", "Match")
                        .WithMany("Tickets")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");
                });

            modelBuilder.Entity("Tickty.Models.Match", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("Tickty.Models.Stadium", b =>
                {
                    b.Navigation("Matches");
                });

            modelBuilder.Entity("Tickty.Models.Ticket", b =>
                {
                    b.Navigation("Bills");
                });

            modelBuilder.Entity("Tickty.Models.User", b =>
                {
                    b.Navigation("Bills");
                });
#pragma warning restore 612, 618
        }
    }
}
